name: Daily Playwright Tests

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright dependencies
        run: npx playwright install

      # Set environment variables from secrets
      - name: Set environment variables
        env:
          USERS_USERSINGLEORG_EMAIL: ${{ secrets.USERS_USERSINGLEORG_EMAIL }}
          USERS_USERSINGLEORG_PASSWORD: ${{ secrets.USERS_USERSINGLEORG_PASSWORD }}
          USERS_USERMULTIORG_EMAIL: ${{ secrets.USERS_USERMULTIORG_EMAIL }}
          USERS_USERMULTIORG_PASSWORD: ${{ secrets.USERS_USERMULTIORG_PASSWORD }}
          LOCALE: ${{ secrets.LOCALE }}
        run: echo "Environment variables set."

      - name: Debug Environment Variables
        run: env

      # Run Playwright tests
      - name: Run Playwright tests
        env:
          USERS_USERSINGLEORG_EMAIL: ${{ secrets.USERS_USERSINGLEORG_EMAIL }}
          USERS_USERSINGLEORG_PASSWORD: ${{ secrets.USERS_USERSINGLEORG_PASSWORD }}
          USERS_USERMULTIORG_EMAIL: ${{ secrets.USERS_USERMULTIORG_EMAIL }}
          USERS_USERMULTIORG_PASSWORD: ${{ secrets.USERS_USERMULTIORG_PASSWORD }}
          LOCALE: ${{ secrets.LOCALE }}
        run: ENV=test npx playwright test
